export const defaultData = [
    {
        aid: 'M11-1',
        a_name: 'Matematicas',
        did: 1006245153,
        status: 'Activo',
    },
    {
        aid: 'C11-1',
        a_name: 'Castellano',
        did: 1006243153,
        status: 'Inactivo',
    },
    {
        aid: 'I11-1',
        a_name: 'Ingles',
        did: 1006243352,
        status: 'Inactivo',
    },
    {
        aid: 'T11-1',
        a_name: 'Tecnologia',
        did: 1006243342,
        status: 'Inactivo',
    },
    {
        aid: 'F11-1',
        a_name: 'Fisica',
        did: 1006243105,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Clara',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Doggerti',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Lei',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Luis',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Pedro',
        lastName: 'Wen',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Tanner',
        lastName: 'Linsley',
        age: 24,
        status: 'Activo',
    },
    {
        name: 'Marcus',
        lastName: 'Lawos',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Bertha',
        lastName: 'Clegain',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Martha',
        lastName: 'Gordom',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Luis',
        lastName: 'Foxcius',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Clara',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Lei',
        lastName: 'Valezca',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Luis',
        lastName: 'Doggerti',
        age: 18,
        status: 'Activo',
    },
    {
        name: 'Jerom',
        lastName: 'Maison',
        age: 18,
        status: 'Inactivo',
    },
    {
        name: 'Pedro',
        lastName: 'Wen',
        age: 18,
        status: 'Activo',
    },
]